import { Category, ImageItem, User, Board, Notification } from '../types';

export const generateSampleSvg = (title: string, category: string, primaryColor: string, secondaryColor: string, width = 800, height = 1000) => {
  return `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}"><defs><linearGradient id="g" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="${encodeURIComponent(primaryColor)}"/><stop offset="100%" stop-color="${encodeURIComponent(secondaryColor)}"/></linearGradient><pattern id="p" width="40" height="40" patternUnits="userSpaceOnUse"><circle cx="20" cy="20" r="2" fill="white" opacity="0.15"/></pattern></defs><rect width="100%" height="100%" fill="url(%23g)"/><rect width="100%" height="100%" fill="url(%23p)"/><circle cx="${width/2}" cy="${height/2 - 40}" r="${Math.min(width, height)/4}" fill="none" stroke="white" stroke-width="4" opacity="0.25"/><text x="50%" y="48%" fill="white" font-family="sans-serif" font-size="30" font-weight="800" text-anchor="middle">${encodeURIComponent(title)}</text><text x="50%" y="54%" fill="rgba(255,255,255,0.8)" font-family="sans-serif" font-size="18" font-weight="600" text-anchor="middle">⚡ ${encodeURIComponent(category)}</text></svg>`;
};

export const INITIAL_USER: User = {
  id: 'user_demo_123',
  username: 'alex_designer',
  displayName: 'Alex Morgan',
  email: 'alex.morgan@pinscape.local',
  avatar: generateSampleSvg('Alex', 'Creator', '#6366f1', '#a855f7', 200, 200),
  bio: 'Visual designer & photography enthusiast. Creating modern aesthetic spaces and curation.',
  website: 'https://alexmorgan.design',
  followersCount: 1420,
  followingCount: 385,
  totalImages: 12,
  createdAt: new Date(Date.now() - 86400000 * 120).toISOString(),
};

export const CATEGORIES: Category[] = [
  { id: 'cat_1', name: 'Photography', slug: 'photography', description: 'Stunning moments captured around the globe', coverUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_2', name: 'Nature', slug: 'nature', description: 'Lush landscapes, oceans, mountains & forests', coverUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_3', name: 'Technology', slug: 'technology', description: 'Futuristic gadgets, neon tech & hardware', coverUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_4', name: 'Architecture', slug: 'architecture', description: 'Minimalist structures & urban marvels', coverUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_5', name: 'Travel', slug: 'travel', description: 'Wanderlust destinations & hidden gems', coverUrl: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_6', name: 'Cars', slug: 'cars', description: 'Supercars, vintage automobiles & speed', coverUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_7', name: 'Fashion', slug: 'fashion', description: 'Haute couture, street style & aesthetics', coverUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_8', name: 'Food', slug: 'food', description: 'Gourmet cuisine, coffee & sweet treats', coverUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_9', name: 'Animals', slug: 'animals', description: 'Wild species, pets & majestic fauna', coverUrl: 'https://images.unsplash.com/photo-1474511320723-9a56873867b5?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_10', name: 'AI Art', slug: 'ai-art', description: 'Surreal AI renders & synthetic imagination', coverUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_11', name: 'Illustration', slug: 'illustration', description: 'Digital painting, anime art & character design', coverUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_12', name: 'Wallpapers', slug: 'wallpapers', description: 'HD 4K backgrounds for desktop & mobile', coverUrl: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_13', name: '3D', slug: '3d', description: 'Cinema 4D, Blender renders & spatial geometry', coverUrl: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_14', name: 'Abstract', slug: 'abstract', description: 'Fluid colors, geometric shapes & mood art', coverUrl: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_15', name: 'UI/UX', slug: 'ui-ux', description: 'Mobile apps, web dashboards & design systems', coverUrl: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=600&q=80' },
];

export const INITIAL_BOARDS: Board[] = [
  {
    id: 'board_1',
    userId: INITIAL_USER.id,
    name: 'Minimal Architecture',
    description: 'Clean lines, concrete structures, and natural shadow play.',
    coverImageUrl: generateSampleSvg('Minimal Architecture', 'Architecture', '#0f172a', '#3b82f6', 600, 400),
    isPrivate: false,
    imageIds: ['img_1', 'img_8', 'img_15'],
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'board_2',
    userId: INITIAL_USER.id,
    name: 'Cyberpunk & Synthwave',
    description: 'Neon lighting, rain-slicked city streets and dark futuristic aesthetics.',
    coverImageUrl: generateSampleSvg('Cyberpunk Synthwave', 'Technology', '#831843', '#06b6d4', 600, 400),
    isPrivate: false,
    imageIds: ['img_2', 'img_9', 'img_14'],
    createdAt: new Date(Date.now() - 86400000 * 20).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: 'board_3',
    userId: INITIAL_USER.id,
    name: 'Serene Nature Escapes',
    description: 'Breathtaking mountain peaks, misty pine forests and quiet waters.',
    coverImageUrl: generateSampleSvg('Serene Nature', 'Nature', '#064e3b', '#10b981', 600, 400),
    isPrivate: true,
    imageIds: ['img_3', 'img_7', 'img_12'],
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
];

export const INITIAL_IMAGES: ImageItem[] = [
  {
    id: 'img_local_1',
    userId: INITIAL_USER.id,
    title: 'IMG20250813181945',
    description: 'A captured moment from the collection.',
    url: '/img/IMG20250813181945.jpg',
    thumbnail: '/img/IMG20250813181945.jpg',
    aspectRatio: 1.33,
    width: 1600,
    height: 1200,
    category: 'Photography',
    tags: ['photography', 'moment', 'memory'],
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    likesCount: 45,
    savesCount: 22,
    viewsCount: 310,
    downloadsCount: 8,
    privacy: 'public',
    status: 'published',
    creator: {
      id: INITIAL_USER.id,
      username: INITIAL_USER.username,
      displayName: INITIAL_USER.displayName,
      avatar: INITIAL_USER.avatar,
    },
  },
  {
    id: 'img_local_2',
    userId: INITIAL_USER.id,
    title: 'IMG20250813182425',
    description: 'A captured moment from the collection.',
    url: '/img/IMG20250813182425.jpg',
    thumbnail: '/img/IMG20250813182425.jpg',
    aspectRatio: 0.75,
    width: 1200,
    height: 1600,
    category: 'Photography',
    tags: ['photography', 'moment', 'memory'],
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    likesCount: 62,
    savesCount: 31,
    viewsCount: 445,
    downloadsCount: 12,
    privacy: 'public',
    status: 'published',
    creator: {
      id: INITIAL_USER.id,
      username: INITIAL_USER.username,
      displayName: INITIAL_USER.displayName,
      avatar: INITIAL_USER.avatar,
    },
  },
  {
    id: 'img_local_3',
    userId: INITIAL_USER.id,
    title: 'IMG20250814091537',
    description: 'A captured moment from the collection.',
    url: '/img/IMG20250814091537.jpg',
    thumbnail: '/img/IMG20250814091537.jpg',
    aspectRatio: 1.33,
    width: 1600,
    height: 1200,
    category: 'Photography',
    tags: ['photography', 'moment', 'memory'],
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    likesCount: 88,
    savesCount: 41,
    viewsCount: 620,
    downloadsCount: 19,
    privacy: 'public',
    status: 'published',
    creator: {
      id: INITIAL_USER.id,
      username: INITIAL_USER.username,
      displayName: INITIAL_USER.displayName,
      avatar: INITIAL_USER.avatar,
    },
  },
  {
    id: 'img_local_4',
    userId: INITIAL_USER.id,
    title: 'IMG20250814091548',
    description: 'A captured moment from the collection.',
    url: '/img/IMG20250814091548.jpg',
    thumbnail: '/img/IMG20250814091548.jpg',
    aspectRatio: 0.75,
    width: 1200,
    height: 1600,
    category: 'Photography',
    tags: ['photography', 'moment', 'memory'],
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    likesCount: 54,
    savesCount: 27,
    viewsCount: 390,
    downloadsCount: 10,
    privacy: 'public',
    status: 'published',
    creator: {
      id: INITIAL_USER.id,
      username: INITIAL_USER.username,
      displayName: INITIAL_USER.displayName,
      avatar: INITIAL_USER.avatar,
    },
  },
  {
    id: 'img_local_5',
    userId: INITIAL_USER.id,
    title: 'IMG20250814091731',
    description: 'A captured moment from the collection.',
    url: '/img/IMG20250814091731.jpg',
    thumbnail: '/img/IMG20250814091731.jpg',
    aspectRatio: 1.33,
    width: 1600,
    height: 1200,
    category: 'Photography',
    tags: ['photography', 'moment', 'memory'],
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    likesCount: 73,
    savesCount: 35,
    viewsCount: 510,
    downloadsCount: 15,
    privacy: 'public',
    status: 'published',
    creator: {
      id: INITIAL_USER.id,
      username: INITIAL_USER.username,
      displayName: INITIAL_USER.displayName,
      avatar: INITIAL_USER.avatar,
    },
  },
  {
    id: 'img_local_6',
    userId: INITIAL_USER.id,
    title: 'IMG20250814144232',
    description: 'A captured moment from the collection.',
    url: '/img/IMG20250814144232.jpg',
    thumbnail: '/img/IMG20250814144232.jpg',
    aspectRatio: 1.33,
    width: 1600,
    height: 1200,
    category: 'Photography',
    tags: ['photography', 'moment', 'memory'],
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    likesCount: 91,
    savesCount: 48,
    viewsCount: 670,
    downloadsCount: 21,
    privacy: 'public',
    status: 'published',
    creator: {
      id: INITIAL_USER.id,
      username: INITIAL_USER.username,
      displayName: INITIAL_USER.displayName,
      avatar: INITIAL_USER.avatar,
    },
  },
  {
    id: 'img_local_7',
    userId: INITIAL_USER.id,
    title: 'IMG20250814160730',
    description: 'A captured moment from the collection.',
    url: '/img/IMG20250814160730.jpg',
    thumbnail: '/img/IMG20250814160730.jpg',
    aspectRatio: 0.75,
    width: 1200,
    height: 1600,
    category: 'Photography',
    tags: ['photography', 'moment', 'memory'],
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    likesCount: 38,
    savesCount: 18,
    viewsCount: 260,
    downloadsCount: 6,
    privacy: 'public',
    status: 'published',
    creator: {
      id: INITIAL_USER.id,
      username: INITIAL_USER.username,
      displayName: INITIAL_USER.displayName,
      avatar: INITIAL_USER.avatar,
    },
  },
  {
    id: 'img_local_8',
    userId: INITIAL_USER.id,
    title: 'IMG20250814192659',
    description: 'A captured moment from the collection.',
    url: '/img/IMG20250814192659.jpg',
    thumbnail: '/img/IMG20250814192659.jpg',
    aspectRatio: 1.33,
    width: 1600,
    height: 1200,
    category: 'Photography',
    tags: ['photography', 'moment', 'memory'],
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    likesCount: 29,
    savesCount: 14,
    viewsCount: 195,
    downloadsCount: 4,
    privacy: 'public',
    status: 'published',
    creator: {
      id: INITIAL_USER.id,
      username: INITIAL_USER.username,
      displayName: INITIAL_USER.displayName,
      avatar: INITIAL_USER.avatar,
    },
  },
  {
    id: 'img_local_9',
    userId: INITIAL_USER.id,
    title: 'IMG20250814192706',
    description: 'A captured moment from the collection.',
    url: '/img/IMG20250814192706.jpg',
    thumbnail: '/img/IMG20250814192706.jpg',
    aspectRatio: 0.75,
    width: 1200,
    height: 1600,
    category: 'Photography',
    tags: ['photography', 'moment', 'memory'],
    createdAt: new Date(Date.now() - 86400000 * 9).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 9).toISOString(),
    likesCount: 17,
    savesCount: 9,
    viewsCount: 130,
    downloadsCount: 3,
    privacy: 'public',
    status: 'published',
    creator: {
      id: INITIAL_USER.id,
      username: INITIAL_USER.username,
      displayName: INITIAL_USER.displayName,
      avatar: INITIAL_USER.avatar,
    },
  },
  {
    id: 'img_local_10',
    userId: INITIAL_USER.id,
    title: 'IMG20250815175321',
    description: 'A captured moment from the collection.',
    url: '/img/IMG20250815175321.jpg',
    thumbnail: '/img/IMG20250815175321.jpg',
    aspectRatio: 1.33,
    width: 1600,
    height: 1200,
    category: 'Photography',
    tags: ['photography', 'moment', 'memory'],
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    likesCount: 66,
    savesCount: 33,
    viewsCount: 470,
    downloadsCount: 14,
    privacy: 'public',
    status: 'published',
    creator: {
      id: INITIAL_USER.id,
      username: INITIAL_USER.username,
      displayName: INITIAL_USER.displayName,
      avatar: INITIAL_USER.avatar,
    },
  },
  {
    id: 'img_local_11',
    userId: INITIAL_USER.id,
    title: 'IMG20250815175638',
    description: 'A captured moment from the collection.',
    url: '/img/IMG20250815175638.jpg',
    thumbnail: '/img/IMG20250815175638.jpg',
    aspectRatio: 1.33,
    width: 1600,
    height: 1200,
    category: 'Photography',
    tags: ['photography', 'moment', 'memory'],
    createdAt: new Date(Date.now() - 86400000 * 11).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 11).toISOString(),
    likesCount: 82,
    savesCount: 40,
    viewsCount: 590,
    downloadsCount: 18,
    privacy: 'public',
    status: 'published',
    creator: {
      id: INITIAL_USER.id,
      username: INITIAL_USER.username,
      displayName: INITIAL_USER.displayName,
      avatar: INITIAL_USER.avatar,
    },
  },
  {
    id: 'img_local_12',
    userId: INITIAL_USER.id,
    title: 'IMG_20250815_130726',
    description: 'A captured moment from the collection.',
    url: '/img/IMG_20250815_130726.jpg',
    thumbnail: '/img/IMG_20250815_130726.jpg',
    aspectRatio: 1.33,
    width: 1600,
    height: 1200,
    category: 'Photography',
    tags: ['photography', 'moment', 'memory'],
    createdAt: new Date(Date.now() - 86400000 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 12).toISOString(),
    likesCount: 104,
    savesCount: 52,
    viewsCount: 730,
    downloadsCount: 25,
    privacy: 'public',
    status: 'published',
    creator: {
      id: INITIAL_USER.id,
      username: INITIAL_USER.username,
      displayName: INITIAL_USER.displayName,
      avatar: INITIAL_USER.avatar,
    },
  },
];


export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif_1',
    userId: INITIAL_USER.id,
    type: 'like',
    actorName: 'Kenji Sato',
    actorAvatar: generateSampleSvg('KS', 'User', '#0284c7', '#38bdf8', 200, 200),
    imageId: 'img_4',
    imageThumbnail: generateSampleSvg('Glassmorphic UI', 'UI', '#1e1b4b', '#6366f1', 200, 200),
    text: 'liked your image "Glassmorphic Mobile Dashboard UI"',
    isRead: false,
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'notif_2',
    userId: INITIAL_USER.id,
    type: 'save',
    actorName: 'Elena Rostova',
    actorAvatar: generateSampleSvg('ER', 'User', '#e11d48', '#fb7185', 200, 200),
    imageId: 'img_8',
    imageThumbnail: generateSampleSvg('Latte Art', 'Food', '#78350f', '#f59e0b', 200, 200),
    text: 'saved your photo to board "Morning Aesthetics"',
    isRead: false,
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: 'notif_3',
    userId: INITIAL_USER.id,
    type: 'follow',
    actorName: 'Marcus Vance',
    actorAvatar: generateSampleSvg('MV', 'User', '#7c3aed', '#a78bfa', 200, 200),
    text: 'started following your collections',
    isRead: true,
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: 'notif_4',
    userId: INITIAL_USER.id,
    type: 'comment',
    actorName: 'Sarah Jenkins',
    actorAvatar: generateSampleSvg('SJ', 'User', '#059669', '#34d399', 200, 200),
    imageId: 'img_12',
    imageThumbnail: generateSampleSvg('Sand Dunes', 'Wallpaper', '#431407', '#ea580c', 200, 200),
    text: 'commented: "The color palette in this dune sunset is breathtaking!"',
    isRead: true,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
];
