import { Category, ImageItem, User, Board, Notification } from '../types';

export const generateSampleSvg = (title: string, category: string, primaryColor: string, secondaryColor: string, width = 800, height = 1000) => {
  return `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}"><defs><linearGradient id="g" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="${encodeURIComponent(primaryColor)}"/><stop offset="100%" stop-color="${encodeURIComponent(secondaryColor)}"/></linearGradient><pattern id="p" width="40" height="40" patternUnits="userSpaceOnUse"><circle cx="20" cy="20" r="2" fill="white" opacity="0.15"/></pattern></defs><rect width="100%" height="100%" fill="url(%23g)"/><rect width="100%" height="100%" fill="url(%23p)"/><circle cx="${width/2}" cy="${height/2 - 40}" r="${Math.min(width, height)/4}" fill="none" stroke="white" stroke-width="4" opacity="0.25"/><text x="50%" y="48%" fill="white" font-family="sans-serif" font-size="30" font-weight="800" text-anchor="middle">${encodeURIComponent(title)}</text><text x="50%" y="54%" fill="rgba(255,255,255,0.8)" font-family="sans-serif" font-size="18" font-weight="600" text-anchor="middle">⚡ ${encodeURIComponent(category)}</text></svg>`;
};

export const INITIAL_USER: User = {
  id: 'user_demo_123',
  username: 'alex_designer',
  displayName: 'Alex Morgan',
  email: 'alex.morgan@pinscape.local',
  avatar: generateSampleSvg('Alex', 'Creator', '#6366f1', '#a855f7', 200, 200),
  bio: 'Visual designer & photography enthusiast. Creating modern aesthetic spaces and curation.',
  website: 'https://alexmorgan.design',
  followersCount: 1420,
  followingCount: 385,
  totalImages: 12,
  createdAt: new Date(Date.now() - 86400000 * 120).toISOString(),
};

export const CATEGORIES: Category[] = [
  { id: 'cat_1', name: 'Photography', slug: 'photography', description: 'Stunning moments captured around the globe', coverUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_2', name: 'Nature', slug: 'nature', description: 'Lush landscapes, oceans, mountains & forests', coverUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_3', name: 'Technology', slug: 'technology', description: 'Futuristic gadgets, neon tech & hardware', coverUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_4', name: 'Architecture', slug: 'architecture', description: 'Minimalist structures & urban marvels', coverUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_5', name: 'Travel', slug: 'travel', description: 'Wanderlust destinations & hidden gems', coverUrl: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_6', name: 'Cars', slug: 'cars', description: 'Supercars, vintage automobiles & speed', coverUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_7', name: 'Fashion', slug: 'fashion', description: 'Haute couture, street style & aesthetics', coverUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_8', name: 'Food', slug: 'food', description: 'Gourmet cuisine, coffee & sweet treats', coverUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_9', name: 'Animals', slug: 'animals', description: 'Wild species, pets & majestic fauna', coverUrl: 'https://images.unsplash.com/photo-1474511320723-9a56873867b5?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_10', name: 'AI Art', slug: 'ai-art', description: 'Surreal AI renders & synthetic imagination', coverUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_11', name: 'Illustration', slug: 'illustration', description: 'Digital painting, anime art & character design', coverUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_12', name: 'Wallpapers', slug: 'wallpapers', description: 'HD 4K backgrounds for desktop & mobile', coverUrl: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_13', name: '3D', slug: '3d', description: 'Cinema 4D, Blender renders & spatial geometry', coverUrl: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_14', name: 'Abstract', slug: 'abstract', description: 'Fluid colors, geometric shapes & mood art', coverUrl: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_15', name: 'UI/UX', slug: 'ui-ux', description: 'Mobile apps, web dashboards & design systems', coverUrl: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=600&q=80' },
];

export const INITIAL_BOARDS: Board[] = [
  {
    id: 'board_1',
    userId: INITIAL_USER.id,
    name: 'Minimal Architecture',
    description: 'Clean lines, concrete structures, and natural shadow play.',
    coverImageUrl: generateSampleSvg('Minimal Architecture', 'Architecture', '#0f172a', '#3b82f6', 600, 400),
    isPrivate: false,
    imageIds: ['img_1', 'img_8', 'img_15'],
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'board_2',
    userId: INITIAL_USER.id,
    name: 'Cyberpunk & Synthwave',
    description: 'Neon lighting, rain-slicked city streets and dark futuristic aesthetics.',
    coverImageUrl: generateSampleSvg('Cyberpunk Synthwave', 'Technology', '#831843', '#06b6d4', 600, 400),
    isPrivate: false,
    imageIds: ['img_2', 'img_9', 'img_14'],
    createdAt: new Date(Date.now() - 86400000 * 20).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: 'board_3',
    userId: INITIAL_USER.id,
    name: 'Serene Nature Escapes',
    description: 'Breathtaking mountain peaks, misty pine forests and quiet waters.',
    coverImageUrl: generateSampleSvg('Serene Nature', 'Nature', '#064e3b', '#10b981', 600, 400),
    isPrivate: true,
    imageIds: ['img_3', 'img_7', 'img_12'],
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
];

export const INITIAL_IMAGES: ImageItem[] = [
  {
    id: 'img_gdrive_1',
    userId: INITIAL_USER.id,
    title: 'Group Celebration & Friends Memory',
    description: 'A special memorable group photo with friends captured during an unforgettable event.',
    url: '/group_photo.jpg',
    thumbnail: '/group_photo.jpg',
    aspectRatio: 1.33,
    width: 1600,
    height: 1200,
    category: 'Photography',
    tags: ['friends', 'group', 'celebration', 'memory', 'event', 'photography', 'gathering'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    likesCount: 156,
    savesCount: 84,
    viewsCount: 1240,
    downloadsCount: 45,
    privacy: 'public',
    status: 'published',
    creator: {
      id: INITIAL_USER.id,
      username: INITIAL_USER.username,
      displayName: INITIAL_USER.displayName,
      avatar: INITIAL_USER.avatar,
    },
  },
  {
    id: 'img_1',
    userId: 'user_creator_1',
    title: 'Minimalist Curved Spiral Staircase',
    description: 'Architectural study of sunlight filtering through white marble spiral stairs in Copenhagen.',
    url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
    aspectRatio: 0.75, // tall portrait
    width: 800,
    height: 1066,
    category: 'Architecture',
    tags: ['minimalist', 'white', 'stairs', 'denmark', 'copenhagen', 'interior'],
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    likesCount: 342,
    savesCount: 189,
    viewsCount: 2450,
    downloadsCount: 95,
    privacy: 'public',
    status: 'published',
    creator: {
      id: 'user_creator_1',
      username: 'elena_arch',
      displayName: 'Elena Rostova',
      avatar: generateSampleSvg('ER', 'Creator', '#e11d48', '#fb7185', 200, 200),
    },
  },
  {
    id: 'img_2',
    userId: 'user_creator_2',
    title: 'Neon Tokyo Rain Reflection',
    description: 'Late night Shinjuku alleyway glistening with neon reflections after midnight rainfall.',
    url: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80',
    aspectRatio: 0.67, // portrait 800x1200
    width: 800,
    height: 1200,
    category: 'Photography',
    tags: ['tokyo', 'neon', 'rain', 'japan', 'night', 'street photography'],
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    likesCount: 1280,
    savesCount: 620,
    viewsCount: 8900,
    downloadsCount: 410,
    privacy: 'public',
    status: 'published',
    creator: {
      id: 'user_creator_2',
      username: 'kenji_photo',
      displayName: 'Kenji Sato',
      avatar: generateSampleSvg('KS', 'Creator', '#0284c7', '#38bdf8', 200, 200),
    },
  },
  {
    id: 'img_3',
    userId: 'user_creator_3',
    title: 'Emerald Alpine Lake at Sunrise',
    description: 'Golden hour light illuminating jagged Dolomite mountain peaks mirrored in crystal calm lake.',
    url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    aspectRatio: 1.33, // landscape
    width: 1200,
    height: 900,
    category: 'Nature',
    tags: ['dolomites', 'mountains', 'lake', 'sunrise', 'italy', 'landscape'],
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    likesCount: 950,
    savesCount: 430,
    viewsCount: 6700,
    downloadsCount: 280,
    privacy: 'public',
    status: 'published',
    creator: {
      id: 'user_creator_3',
      username: 'sarah_explores',
      displayName: 'Sarah Jenkins',
      avatar: generateSampleSvg('SJ', 'Creator', '#059669', '#34d399', 200, 200),
    },
  },
  {
    id: 'img_4',
    userId: INITIAL_USER.id,
    title: 'Glassmorphic Mobile Dashboard UI',
    description: 'Dark mode financial tracking interface concept with frosted glass cards and glowing gradients.',
    url: generateSampleSvg('Glassmorphic Dashboard UI', 'UI/UX', '#1e1b4b', '#6366f1', 800, 1000),
    aspectRatio: 0.8,
    width: 800,
    height: 1000,
    category: 'UI/UX',
    tags: ['ui', 'ux', 'dashboard', 'glassmorphism', 'dark mode', 'framer'],
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    likesCount: 610,
    savesCount: 520,
    viewsCount: 4100,
    downloadsCount: 190,
    privacy: 'public',
    status: 'published',
    creator: {
      id: INITIAL_USER.id,
      username: INITIAL_USER.username,
      displayName: INITIAL_USER.displayName,
      avatar: INITIAL_USER.avatar,
    },
  },
  {
    id: 'img_5',
    userId: 'user_creator_4',
    title: 'Irridescent 3D Fluid Sphere Render',
    description: 'Abstract digital sculpture exploring chromatic aberration, specular highlights, and metallic luster.',
    url: generateSampleSvg('Irridescent 3D Sphere', '3D', '#4c1d95', '#c084fc', 900, 900),
    aspectRatio: 1.0,
    width: 900,
    height: 900,
    category: '3D',
    tags: ['3d', 'render', 'octane', 'fluid', 'abstract', 'iridescent', 'blender'],
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    likesCount: 1450,
    savesCount: 980,
    viewsCount: 11200,
    downloadsCount: 670,
    privacy: 'public',
    status: 'published',
    creator: {
      id: 'user_creator_4',
      username: 'marcus_3d',
      displayName: 'Marcus Vance',
      avatar: generateSampleSvg('MV', 'Creator', '#7c3aed', '#a78bfa', 200, 200),
    },
  },
  {
    id: 'img_6',
    userId: 'user_creator_5',
    title: 'Matte Black Vintage Porsche 911',
    description: 'Classic air-cooled Porsche resting under ambient garage floodlights at twilight.',
    url: generateSampleSvg('Vintage Porsche 911', 'Cars', '#18181b', '#52525b', 1200, 800),
    aspectRatio: 1.5,
    width: 1200,
    height: 800,
    category: 'Cars',
    tags: ['porsche', 'supercar', 'matte black', 'vintage', 'automotive', 'garage'],
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    likesCount: 2100,
    savesCount: 1150,
    viewsCount: 15400,
    downloadsCount: 890,
    privacy: 'public',
    status: 'published',
    creator: {
      id: 'user_creator_5',
      username: 'speed_hunter',
      displayName: 'David Ray',
      avatar: generateSampleSvg('DR', 'Creator', '#27272a', '#71717a', 200, 200),
    },
  },
  {
    id: 'img_7',
    userId: 'user_creator_6',
    title: 'Surreal Floating Islands AI Art',
    description: 'Generated artwork featuring floating mossy monoliths bathed in luminescent cosmic clouds.',
    url: generateSampleSvg('Surreal Floating Islands', 'AI Art', '#064e3b', '#06b6d4', 700, 1000),
    aspectRatio: 0.7,
    width: 700,
    height: 1000,
    category: 'AI Art',
    tags: ['ai art', 'midjourney', 'fantasy', 'surreal', 'cosmic', 'floating islands'],
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    likesCount: 890,
    savesCount: 640,
    viewsCount: 7800,
    downloadsCount: 310,
    privacy: 'public',
    status: 'published',
    creator: {
      id: 'user_creator_6',
      username: 'synthetic_dream',
      displayName: 'Aria Chen',
      avatar: generateSampleSvg('AC', 'Creator', '#0d9488', '#2dd4bf', 200, 200),
    },
  },
  {
    id: 'img_8',
    userId: INITIAL_USER.id,
    title: 'Artisanal Latte & Fresh Croissant',
    description: 'Morning light cozy coffee aesthetic with silky fern latte art and flaky butter pastries.',
    url: generateSampleSvg('Cozy Coffee & Latte Art', 'Food', '#78350f', '#f59e0b', 800, 940),
    aspectRatio: 0.85,
    width: 800,
    height: 940,
    category: 'Food',
    tags: ['coffee', 'latte art', 'croissant', 'breakfast', 'cozy', 'flatlay'],
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    likesCount: 430,
    savesCount: 290,
    viewsCount: 3200,
    downloadsCount: 140,
    privacy: 'public',
    status: 'published',
    creator: {
      id: INITIAL_USER.id,
      username: INITIAL_USER.username,
      displayName: INITIAL_USER.displayName,
      avatar: INITIAL_USER.avatar,
    },
  },
  {
    id: 'img_9',
    userId: 'user_creator_7',
    title: 'Cybernetic Neon City Street',
    description: 'Futuristic high-tech metropolis cityscape glowing in shades of violet and cyan.',
    url: generateSampleSvg('Cybernetic Neon City', 'Technology', '#4c1d95', '#06b6d4', 1400, 1000),
    aspectRatio: 1.4,
    width: 1400,
    height: 1000,
    category: 'Technology',
    tags: ['cyberpunk', 'futuristic', 'neon', 'cityscape', 'purple', 'wallpaper'],
    createdAt: new Date(Date.now() - 86400000 * 9).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 9).toISOString(),
    likesCount: 1820,
    savesCount: 1100,
    viewsCount: 14300,
    downloadsCount: 820,
    privacy: 'public',
    status: 'published',
    creator: {
      id: 'user_creator_7',
      username: 'pixel_master',
      displayName: 'Liam O\'Connor',
      avatar: generateSampleSvg('LO', 'Creator', '#6d28d9', '#a78bfa', 200, 200),
    },
  },
  {
    id: 'img_10',
    userId: 'user_creator_8',
    title: 'High Fashion Editorial in Paris',
    description: 'Haute couture monochrome fashion photography on the steps of Palais Garnier.',
    url: generateSampleSvg('Haute Couture Paris', 'Fashion', '#09090b', '#71717a', 650, 1000),
    aspectRatio: 0.65,
    width: 650,
    height: 1000,
    category: 'Fashion',
    tags: ['fashion', 'paris', 'editorial', 'haute couture', 'black and white', 'model'],
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    likesCount: 940,
    savesCount: 510,
    viewsCount: 7100,
    downloadsCount: 230,
    privacy: 'public',
    status: 'published',
    creator: {
      id: 'user_creator_8',
      username: 'vogue_claire',
      displayName: 'Claire Laurent',
      avatar: generateSampleSvg('CL', 'Creator', '#be185d', '#f472b6', 200, 200),
    },
  },
  {
    id: 'img_11',
    userId: 'user_creator_9',
    title: 'Golden Retriever in Autumn Forest',
    description: 'Joyful retriever running through golden fallen maple leaves in Pacific Northwest woodland.',
    url: generateSampleSvg('Golden Retriever Autumn', 'Animals', '#9a3412', '#f97316', 1200, 1000),
    aspectRatio: 1.2,
    width: 1200,
    height: 1000,
    category: 'Animals',
    tags: ['dog', 'golden retriever', 'autumn', 'nature', 'pets', 'happy'],
    createdAt: new Date(Date.now() - 86400000 * 11).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 11).toISOString(),
    likesCount: 1650,
    savesCount: 720,
    viewsCount: 10900,
    downloadsCount: 540,
    privacy: 'public',
    status: 'published',
    creator: {
      id: 'user_creator_9',
      username: 'paws_photo',
      displayName: 'Oliver Smith',
      avatar: generateSampleSvg('OS', 'Creator', '#c2410c', '#fb923c', 200, 200),
    },
  },
  {
    id: 'img_12',
    userId: INITIAL_USER.id,
    title: 'Minimalist Sand Dunes at Sunset',
    description: 'Soft pastel gradients over rolling desert dunes under a twilight violet sky.',
    url: generateSampleSvg('Minimal Sand Dunes', 'Wallpapers', '#431407', '#ea580c', 720, 1000),
    aspectRatio: 0.72,
    width: 720,
    height: 1000,
    category: 'Wallpapers',
    tags: ['wallpaper', 'desert', 'minimalist', 'dunes', 'sunset', 'gradient'],
    createdAt: new Date(Date.now() - 86400000 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 12).toISOString(),
    likesCount: 780,
    savesCount: 690,
    viewsCount: 6200,
    downloadsCount: 480,
    privacy: 'public',
    status: 'published',
    creator: {
      id: INITIAL_USER.id,
      username: INITIAL_USER.username,
      displayName: INITIAL_USER.displayName,
      avatar: INITIAL_USER.avatar,
    },
  },
  {
    id: 'img_13',
    userId: 'user_creator_10',
    title: 'Vector Isometric Character Illustration',
    description: 'Playful isometric scene of creative professionals collaborating in a modern plant-filled studio.',
    url: generateSampleSvg('Isometric Studio Design', 'Illustration', '#0369a1', '#38bdf8', 1100, 1000),
    aspectRatio: 1.1,
    width: 1100,
    height: 1000,
    category: 'Illustration',
    tags: ['illustration', 'isometric', 'vector', 'flat design', 'digital art', 'creative'],
    createdAt: new Date(Date.now() - 86400000 * 13).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 13).toISOString(),
    likesCount: 520,
    savesCount: 410,
    viewsCount: 3800,
    downloadsCount: 160,
    privacy: 'public',
    status: 'published',
    creator: {
      id: 'user_creator_10',
      username: 'vector_ninja',
      displayName: 'MIA Wang',
      avatar: generateSampleSvg('MW', 'Creator', '#0284c7', '#38bdf8', 200, 200),
    },
  },
  {
    id: 'img_14',
    userId: 'user_creator_1',
    title: 'Fluid Acrylic Pastel Waves',
    description: 'Macro photograph of swirling pink, teal, and metallic gold acrylic paint textures.',
    url: generateSampleSvg('Fluid Acrylic Waves', 'Abstract', '#831843', '#ec4899', 800, 1000),
    aspectRatio: 0.8,
    width: 800,
    height: 1000,
    category: 'Abstract',
    tags: ['abstract', 'fluid art', 'pastel', 'acrylic', 'pink', 'texture', 'gold'],
    createdAt: new Date(Date.now() - 86400000 * 14).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 14).toISOString(),
    likesCount: 1120,
    savesCount: 890,
    viewsCount: 9400,
    downloadsCount: 510,
    privacy: 'public',
    status: 'published',
    creator: {
      id: 'user_creator_1',
      username: 'elena_arch',
      displayName: 'Elena Rostova',
      avatar: generateSampleSvg('ER', 'Creator', '#be185d', '#f472b6', 200, 200),
    },
  },
  {
    id: 'img_15',
    userId: 'user_creator_3',
    title: 'Santorini White Cliffside Sunset',
    description: 'Iconic blue-domed Aegean churches overlooking calm caldera sea during Mediterranean sunset.',
    url: generateSampleSvg('Santorini Cliffside Sunset', 'Travel', '#1e3a8a', '#3b82f6', 1350, 1000),
    aspectRatio: 1.35,
    width: 1350,
    height: 1000,
    category: 'Travel',
    tags: ['greece', 'santorini', 'travel', 'mediterranean', 'sunset', 'vacation'],
    createdAt: new Date(Date.now() - 86400000 * 15).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 15).toISOString(),
    likesCount: 2450,
    savesCount: 1380,
    viewsCount: 18900,
    downloadsCount: 980,
    privacy: 'public',
    status: 'published',
    creator: {
      id: 'user_creator_3',
      username: 'sarah_explores',
      displayName: 'Sarah Jenkins',
      avatar: generateSampleSvg('SJ', 'Creator', '#1d4ed8', '#60a5fa', 200, 200),
    },
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif_1',
    userId: INITIAL_USER.id,
    type: 'like',
    actorName: 'Kenji Sato',
    actorAvatar: generateSampleSvg('KS', 'User', '#0284c7', '#38bdf8', 200, 200),
    imageId: 'img_4',
    imageThumbnail: generateSampleSvg('Glassmorphic UI', 'UI', '#1e1b4b', '#6366f1', 200, 200),
    text: 'liked your image "Glassmorphic Mobile Dashboard UI"',
    isRead: false,
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'notif_2',
    userId: INITIAL_USER.id,
    type: 'save',
    actorName: 'Elena Rostova',
    actorAvatar: generateSampleSvg('ER', 'User', '#e11d48', '#fb7185', 200, 200),
    imageId: 'img_8',
    imageThumbnail: generateSampleSvg('Latte Art', 'Food', '#78350f', '#f59e0b', 200, 200),
    text: 'saved your photo to board "Morning Aesthetics"',
    isRead: false,
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: 'notif_3',
    userId: INITIAL_USER.id,
    type: 'follow',
    actorName: 'Marcus Vance',
    actorAvatar: generateSampleSvg('MV', 'User', '#7c3aed', '#a78bfa', 200, 200),
    text: 'started following your collections',
    isRead: true,
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: 'notif_4',
    userId: INITIAL_USER.id,
    type: 'comment',
    actorName: 'Sarah Jenkins',
    actorAvatar: generateSampleSvg('SJ', 'User', '#059669', '#34d399', 200, 200),
    imageId: 'img_12',
    imageThumbnail: generateSampleSvg('Sand Dunes', 'Wallpaper', '#431407', '#ea580c', 200, 200),
    text: 'commented: "The color palette in this dune sunset is breathtaking!"',
    isRead: true,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
];
